version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: gradle-v1-
      - android/restore-build-cache:
          cache-prefix: build-v1-
      - android/change-java-version:
          java-version: 17
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: 
            ./gradlew androidDependencies
      - run:
          name: Check java version
          command:
            java -version
      - run:
          name: Run Build
          command:
            ./gradlew build
      - android/save-gradle-cache:
          cache-prefix: gradle-v1-
      - android/save-build-cache:
          cache-prefix: build-v1-
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
