version: 2.1
 
orbs:
  android: circleci/android@2.3.0
 
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Install jdk 17
          command:
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            java -version
      - run:
          name: Download Dependencies
          command: 
            ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Install jdk 17
          command:
            java -version
      - run:
          name: Run Build
          command:
            ./gradlew build
      - run:
          name: Check java version
          command:
            java -version
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
