# Workflow name
name: Build
on:
# When it will be triggered
# And in which branch
  pull_request:
  push:
    branches:
      - main
# Where will they run
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      ## Checkout our repository ###
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v3.11.0
        with:
          distribution: oracle
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Chmod permissions
        run: sudo chmod +x ./gradlew
          
      - name: Execute Gradle build
        run: ./gradlew build
        
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run Kotlin Linter
        run: ./gradlew lint test
        
      - name: Cache
        uses: actions/cache@v3.2.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/.android/cache
          # An explicit key for restoring and saving the cache
          key: 123
